---
- name: "Linux userland config"
  hosts: localhost
  become: true
  become_user: ubuntu
  gather_facts: true
  vars:
    the_user: "{{ ansible_user_id }}"
  tasks:
    - name: Hushlogin
      file:
        path: "~/.hushlogin"
        state: touch
        mode: '0644'
        access_time: preserve
        modification_time: preserve
    - name: byobu preferences directory
      file:
        path: "~/.byobu"
        state: directory
        mode: '0755'
    - name: disable byobu welcome message
      file:
        path: "~/.byobu/.welcome-displayed"
        state: touch
        mode: '0644'
        access_time: preserve
        modification_time: preserve
    - name: Set login shell of user {{ ansible_env.USER }} to `/usr/bin/zsh` with `usermod`
      ansible.builtin.command: usermod --shell /usr/bin/zsh {{ ansible_env.USER }}
      become: true
      changed_when: false
