---
- name: "Linux userland config"
  hosts: localhost
  become: true
  become_user: ubuntu
  gather_facts: true
  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: "ubuntu"
          oh_my_zsh:
            theme: agnoster
            plugins:
              - git
              - zsh-syntax-highlighting
              - zsh-autosuggestions
              - zsh-completions
              - terraform
              - docker
      loop: "{{ userlist }}"
  tasks:
    - name: Hushlogin
      file:
        path: "~/.hushlogin"
        state: touch
        mode: '0644'
        access_time: preserve
        modification_time: preserve
    - name: byobu preferences directory
      file:
        path: "~/.byobu"
        state: directory
        mode: '0755'
    - name: disable byobu welcome message
      file:
        path: "~/.byobu/.welcome-displayed"
        state: touch
        mode: '0644'
        access_time: preserve
        modification_time: preserve

