---
- name: "Linux userland config"
  hosts: localhost
  gather_facts: true
  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: "ubuntu"
          oh_my_zsh:
            theme: agnoster
            plugins:
              - git
              - zsh-syntax-highlighting
              - zsh-autosuggestions
              - zsh-completions
              - terraform
              - docker
  tasks:
    - name: Hushlogin
      file:
        path: "/home/ubuntu/.hushlogin"
        state: touch
        mode: '0644'
        access_time: preserve
        modification_time: preserve
        user: ubuntu
        group: ubuntu
    - name: byobu preferences directory
      file:
        path: "/home/ubuntu/.byobu"
        state: directory
        mode: '0755'
        user: ubuntu
        group: ubuntu
    - name: disable byobu welcome message
      file:
        path: "/home/ubuntu/.byobu/.welcome-displayed"
        state: touch
        mode: '0644'
        access_time: preserve
        modification_time: preserve
        user: ubuntu
        group: ubuntu

