---
- name: "Linux userland config"
  hosts: localhost
  become: true
  become_user: ubuntu
  gather_facts: true

  tasks:
    - name: Hushlogin
      file:
        path: "~/.hushlogin"
        state: touch
        mode: '0644'
