---
- name: "Linux userland config"
  hosts: localhost
  become: true
  become_user: ubuntu
  gather_facts: true

  tasks:
    - name: Hushlogin
      file:
        path: "~/.hushlogin"
        state: touch
        mode: '0644'
        changed_when: False
    - name: byobu preferences directory
      file:
        path: "~/.byobu"
        state: directory
        mode: '0755'
        changed_when: False
    - name: disable byobu welcome message
      file:
        path: "~/.byobu/.welcome-displayed"
        state: touch
        mode: '0644'
        changed_when: False
