---
- name: "Linux userland config"
  hosts: localhost
  gather_facts: true
  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: "ubuntu"
          oh_my_zsh:
            theme: agnoster
            plugins:
              - git
              - zsh-syntax-highlighting
              - zsh-autosuggestions
              - terraform
              - docker
              - kubectl
              - ansible
              - colorize
              - cp
              - fzf
              - gh
              - gitignore
              - helm
              - history
              - jsontools
              - sudo
              - ubuntu
              - zsh-interactive-cd
              - zsh-navigation-tools
              - vscode
  tasks:
    - name: Configure Ansible
      become_user: ubuntu
      become: yes
      ini_file:
        path: /home/ubuntu/ansible.cfg
        section: "colors"
        option: "verbose"
        value: "green"
    - name: Hushlogin
      file:
        path: "/home/ubuntu/.hushlogin"
        state: touch
        mode: '0644'
        access_time: preserve
        modification_time: preserve
        owner: ubuntu

              git config --global user.name "Your Name"
    git config --global user.email you@example.com

    - name: byobu preferences directory
      file:
        path: "/home/ubuntu/.byobu"
        state: directory
        mode: '0755'
        owner: ubuntu
    - name: disable byobu welcome message
      file:
        path: "/home/ubuntu/.byobu/.welcome-displayed"
        state: touch
        mode: '0644'
        access_time: preserve
        modification_time: preserve
        owner: ubuntu
    - name: Install zsh autosuggestions
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
        dest: /home/ubuntu/.oh-my-zsh/plugins/zsh-autosuggestions
        force: yes
      become: yes
      become_user: ubuntu
      register: autosuggestions
      changed_when: ( autosuggestions.remote_url_changed is not defined or autosuggestions.remote_url_changed ) 
    - name: Install zsh syntax-highlighting
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: /home/ubuntu/.oh-my-zsh/plugins/zsh-syntax-highlighting
        force: yes
      become: yes
      become_user: ubuntu
      register: syntaxhighlighting
      changed_when: ( syntaxhighlighting.remote_url_changed is not defined or syntaxhighlighting.remote_url_changed ) 
    - name: Ensure .vim/{autoload,bundle} directory exists
      file:
        path: "{{ item }}"
        state: directory
        recurse: no
        mode: 0750
        owner: ubuntu
      loop:
        - "/home/ubuntu/.vim"
        - "/home/ubuntu/.vim/autoload"
        - "/home/ubuntu/.vim/bundle"
    - name: Ensure Pathogen is in place
      get_url:
        dest: "/home/ubuntu/.vim/autoload/pathogen.vim"
        url: https://tpo.pe/pathogen.vim
      become: yes
      become_user: ubuntu
    - name: Deploy plugins
      git:
        dest: "/home/ubuntu/.vim/bundle/{{ item.name }}"
        repo: "{{ item.url }}"
        clone: yes
        update: yes
        recursive: no
      become: yes
      become_user: ubuntu
      loop:
      - name: vim-airline
        url: https://github.com/vim-airline/vim-airline
      - name: nerdtree
        url: https://github.com/preservim/nerdtree
      - name: fzf-vim
        url: https://github.com/junegunn/fzf.vim
      - name: vim-gitgutter
        url: https://github.com/airblade/vim-gitgutter
      - name: vim-fugitive
        url: https://github.com/tpope/vim-fugitive
      - name: vim-floaterm
        url: https://github.com/voldikss/vim-floaterm
    - name: Ensure .vimrc config in place
      copy:
        src: vimrc
        dest: "/home/ubuntu/.vimrc"
        backup: yes
        mode: 0640
        owner: ubuntu
