---
- name: "Linux userland config"
  hosts: localhost
  become: true
  become_user: ubuntu
  gather_facts: true

  tasks:
    - name: Hushlogin
      file:
        path: "~/.hushlogin"
        state: touch
        mode: '0644'
        access_time: preserve
        modification_time: preserve
    - name: disable byobu welcome message
      file:
        path: "~/.byobu/.welcome-displayed"
        state: touch
        mode: '0644'
        access_time: preserve
        modification_time: preserve
